apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: name
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
      - name: cont-02
        image: ubuntu
        ports:
        - containerPort: 80
